#!/usr/bin/env bash
# Regenerate telegram.env from Bitwarden (item: telegram_clawphi in the
# Homelab org). Run after rotating the bot token in Vaultwarden.
#
# Source of truth lives in Bitwarden; this file is just a derived cache for
# scripts/timers that read TELEGRAM_BOT_TOKEN / TELEGRAM_CHAT_ID from env.
set -euo pipefail

ENV_FILE="${TELEGRAM_ENV:-$HOME/repo/environments/envs/telegram/telegram.env}"
ITEM_NAME="${TELEGRAM_BW_ITEM:-telegram_clawphi}"
BW_ENV="${BW_AGENT_ENV:-$HOME/.config/bw/agent.env}"

if [[ -z "${BW_CLIENTID:-}" ]]; then
  if [[ -f "$BW_ENV" ]]; then
    # shellcheck disable=SC1090
    source "$BW_ENV"
  else
    echo "BW_CLIENTID not set and $BW_ENV not found" >&2
    exit 1
  fi
fi

bw login --check >/dev/null 2>&1 || bw login --apikey >/dev/null

SESSION="$(bw unlock --passwordenv BW_PASSWORD --raw 2>/dev/null)"
[[ -n "$SESSION" ]] || { echo "bw unlock failed" >&2; exit 1; }
export BW_SESSION="$SESSION"

bw sync >/dev/null

ITEM_JSON="$(bw get item "$ITEM_NAME" 2>/dev/null)" \
  || { echo "bw could not fetch item: $ITEM_NAME" >&2; exit 1; }

TOKEN="$(printf '%s' "$ITEM_JSON" | jq -er '.fields[] | select(.name=="token") | .value')"
CHAT="$(printf '%s' "$ITEM_JSON" | jq -er '.fields[] | select(.name=="chat_id") | .value')"

[[ "$TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]+$ ]] \
  || { echo "token from bw does not look like a Telegram bot token" >&2; exit 1; }

TMP="$(mktemp "${ENV_FILE}.refresh.XXXXXX")"
trap 'rm -f "$TMP"' EXIT
{
  echo "# Generated by envs/telegram/refresh_env.sh from Bitwarden item '$ITEM_NAME'."
  echo "# Source of truth is Vaultwarden; do not hand-edit. Re-run the script after rotation."
  echo "TELEGRAM_BOT_TOKEN=$TOKEN"
  echo "TELEGRAM_CHAT_ID=$CHAT"
  echo
  echo "# Optional overrides:"
  echo "# TELEGRAM_API_BASE=https://api.telegram.org"
  echo "# TELEGRAM_DISABLE_NOTIFICATION=0"
} > "$TMP"
chmod 600 "$TMP"
mv "$TMP" "$ENV_FILE"
trap - EXIT

echo "telegram.env refreshed (token suffix ...${TOKEN: -8}, chat_id $CHAT)"
